name = "https://onedrive-index.darkshadowds08.workers.dev/"
type = "webpack"
workers_dev = true
account_id = "08d00b54be792194d1406de9c04fe3dd"
zone_id = "3fc2c5e23013d19175307aaf28897f04"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "a7fc2f227e2e45bd920d56c4b0feeecc", id = "09b0cf433f394b309d35d1ff3bd0bf39" }
]

[env.staging]
name = "drive-staging"
